//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <stdio.h>
#include <stdlib.h>

int main(){
    int sum = 0,fib1 = 1,fib2 = 2,fib3 = 0;
    while(fib3 < 4000000){
        fib3 = fib1 + fib2;fib1 = fib2;fib2 = fib3;
        if(fib3 % 2 == 0){sum += fib3;}
    }
    printf("%d\n", sum);
    return 0;

}

/*
s = [1,2]
s += [(s := [s[1], s[0] + s[1]]) and s[1] for k in range(4*10**6)]
print(len(s))
soma = 0
for i in s:
    if i%2 == 0: soma +=i 

print(s)
*/